site_name: 'Generative Art'
nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Course Content:
    - Introduction: 01-intro.md
    - Products: 02-products.md
    - Concepts: 03-concepts.md
    - Promt Design: 04-prompts.py
    - Bias: 05-bias.md
    - Fine Tuning: 06-fine-tuning.md

    - Whats Next: 08-whats-next.md
  - Activities:
    - Introduction: activities/01-intro.md
    - Dall-E 2: activities/02-dalle2.md
    - Midjourney: activities/03-midjournet.md
  - Glossary: glossary.md
  - References: references.md
  - Contacts: contacts.md

site_description: 'Generative Art: Creative Commons licensed content for CoderDojo Twin Cities programs.'
site_author: 'Dan McCreary, Arun Batchu'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/generative-art'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite:
      linenums: true
